"use client";

import Link from "next/link";
import { useState } from "react";

// Shared mock data store — in real app this comes from Supabase
export const suppliersData = [
  {
    id: "SUP-001",
    name: "Shaft Engineering (Pty) Ltd",
    category: "Engineering",
    status: "Active",
    bbbee: "Level 2",
    contact: "sarah@shafteng.co.za",
    contactName: "Sarah van der Merwe",
    phone: "+27 12 555 0101",
    spend: "R12.4M",
    risk: "Low",
    rating: 4.8,
    address: "12 Industrial Rd, Centurion, Gauteng",
    registration: "2002/034521/07",
    vatNumber: "4120987654",
    description: "Leading underground shaft engineering firm specialising in sinking, lining, and equipping of vertical and inclined shafts for the gold and platinum mining sectors.",
    certifications: ["ISO 9001:2015", "ISO 45001:2018", "OHSAS 18001"],
    contracts: [
      { id: "CON-A1", name: "Shaft 3 Extension", value: "R4.2M", status: "Active", expiry: "2027-03-31" },
      { id: "CON-A2", name: "Ventilation Upgrade", value: "R2.8M", status: "Active", expiry: "2026-12-15" },
      { id: "CON-A3", name: "Shaft 1 Maintenance", value: "R1.4M", status: "Completed", expiry: "2025-12-01" },
    ],
  },
  {
    id: "SUP-002",
    name: "DrillMaster Inc",
    category: "Equipment",
    status: "Active",
    bbbee: "Level 4",
    contact: "ops@drillmaster.co.za",
    contactName: "Pieter Botha",
    phone: "+27 11 444 0202",
    spend: "R7.8M",
    risk: "High",
    rating: 3.2,
    address: "44 Mining Ave, Springs, Gauteng",
    registration: "1998/112233/07",
    vatNumber: "4098765432",
    description: "Supplier of drilling equipment, spare parts, and consumables for opencast and underground mining operations.",
    certifications: ["ISO 9001:2015"],
    contracts: [
      { id: "CON-B1", name: "Drill Rig Lease", value: "R3.6M", status: "Active", expiry: "2026-09-30" },
    ],
  },
  {
    id: "SUP-003",
    name: "BlastPro Solutions",
    category: "Explosives",
    status: "Active",
    bbbee: "Level 1",
    contact: "info@blastpro.co.za",
    contactName: "Amahle Zulu",
    phone: "+27 13 333 0303",
    spend: "R4.2M",
    risk: "Medium",
    rating: 4.5,
    address: "7 Explosive Rd, Witbank, Mpumalanga",
    registration: "2005/056789/07",
    vatNumber: "4112345678",
    description: "Licensed explosives supplier and blasting contractor with full DMRE compliance for surface and underground operations.",
    certifications: ["ISO 9001:2015", "DMRE Licence", "ISO 45001:2018"],
    contracts: [
      { id: "CON-C1", name: "Blasting Services 2026", value: "R2.1M", status: "Active", expiry: "2026-12-31" },
      { id: "CON-C2", name: "Explosive Supply", value: "R1.1M", status: "Active", expiry: "2026-08-31" },
    ],
  },
  {
    id: "SUP-004",
    name: "SafeRoute Logistics",
    category: "Transport",
    status: "Suspended",
    bbbee: "Level 3",
    contact: "fleet@saferoute.co.za",
    contactName: "Bongani Nkosi",
    phone: "+27 14 222 0404",
    spend: "R2.1M",
    risk: "High",
    rating: 2.8,
    address: "99 Logistics Park, Rustenburg, NW",
    registration: "2010/078901/07",
    vatNumber: "4034567890",
    description: "Mining logistics and personnel transport services across the Bushveld Complex.",
    certifications: [],
    contracts: [],
  },
  {
    id: "SUP-005",
    name: "TunnelTech Contractors",
    category: "Engineering",
    status: "Active",
    bbbee: "Level 2",
    contact: "projects@tunneltech.co.za",
    contactName: "Jan du Toit",
    phone: "+27 18 111 0505",
    spend: "R18.7M",
    risk: "Low",
    rating: 4.9,
    address: "22 Tunnel Drive, Klerksdorp, NW",
    registration: "1995/023456/07",
    vatNumber: "4056789012",
    description: "Specialist underground tunnel construction and development contractor with 30+ years in gold and platinum mining.",
    certifications: ["ISO 9001:2015", "ISO 45001:2018", "ISO 14001:2015", "OHSAS 18001"],
    contracts: [
      { id: "CON-E1", name: "Level 34 Development", value: "R8.4M", status: "Active", expiry: "2027-06-30" },
      { id: "CON-E2", name: "Rock Support Programme", value: "R5.2M", status: "Active", expiry: "2026-11-30" },
      { id: "CON-E3", name: "Haulage Upgrade", value: "R3.1M", status: "Completed", expiry: "2025-09-30" },
    ],
  },
  {
    id: "SUP-006",
    name: "Mine Catering Services",
    category: "Catering",
    status: "Active",
    bbbee: "Level 1",
    contact: "tender@minecater.co.za",
    contactName: "Nomsa Dlamini",
    phone: "+27 16 999 0606",
    spend: "R3.5M",
    risk: "Low",
    rating: 4.3,
    address: "5 Food Park, Carletonville, Gauteng",
    registration: "2008/067890/07",
    vatNumber: "4078901234",
    description: "Full-service mine catering and accommodation management for surface and underground mining personnel.",
    certifications: ["ISO 22000:2018", "HACCP"],
    contracts: [
      { id: "CON-F1", name: "Hostel & Catering 2026", value: "R3.5M", status: "Active", expiry: "2026-12-31" },
    ],
  },
  {
    id: "SUP-007",
    name: "GeoScan Technologies",
    category: "IT & Tech",
    status: "Pending",
    bbbee: "Level 5",
    contact: "sales@geoscan.co.za",
    contactName: "Reza Patel",
    phone: "+27 11 777 0707",
    spend: "R1.1M",
    risk: "Low",
    rating: 4.1,
    address: "Tower 3, Sandton City Office Park, Johannesburg",
    registration: "2018/112233/07",
    vatNumber: "4090123456",
    description: "Mining technology solutions including real-time seismic monitoring, geotechnical sensors, and data analytics platforms.",
    certifications: ["ISO 27001:2022"],
    contracts: [
      { id: "CON-G1", name: "Seismic Monitoring SaaS", value: "R1.1M", status: "Pending", expiry: "2027-01-31" },
    ],
  },
];

export const contractorsData = [
  { id: "CON-001", name: "TunnelTech Contractors", type: "Civils", expiry: "2026-08-15", sheq: true, iso: true, permits: true, env: false, status: "Compliant", score: 94, contact: "projects@tunneltech.co.za", phone: "+27 18 111 0505" },
  { id: "CON-002", name: "DrillMaster Inc", type: "Drilling", expiry: "2026-07-01", sheq: true, iso: false, permits: true, env: true, status: "Warning", score: 71, contact: "ops@drillmaster.co.za", phone: "+27 11 444 0202" },
  { id: "CON-003", name: "BlastPro Solutions", type: "Blasting", expiry: "2027-01-20", sheq: true, iso: true, permits: true, env: true, status: "Compliant", score: 98, contact: "info@blastpro.co.za", phone: "+27 13 333 0303" },
  { id: "CON-004", name: "SafeRoute Logistics", type: "Transport", expiry: "2026-06-30", sheq: false, iso: false, permits: true, env: false, status: "Non-Compliant", score: 42, contact: "fleet@saferoute.co.za", phone: "+27 14 222 0404" },
  { id: "CON-005", name: "SteelCraft Fabricators", type: "Engineering", expiry: "2026-12-10", sheq: true, iso: true, permits: false, env: true, status: "Warning", score: 78, contact: "info@steelcraft.co.za", phone: "+27 16 888 0505" },
];

export const jobsData = [
  { id: "JOB-001", title: "Senior Mine Surveyor", department: "Technical", location: "Rustenburg", type: "Permanent", applicants: 12, salary: "R75k–R95k/mo", posted: "2026-06-10", status: "Active", description: "We are seeking an experienced Mine Surveyor to join our Technical Services team. The successful candidate will be responsible for all underground and surface survey work, including setting out, volume calculations, and reef intersection surveys.", requirements: ["B.Tech or BSc in Mine Surveying", "Minimum 5 years underground experience", "Mine Surveyor Certificate of Competency", "Proficient in Surpac/Datamine"] },
  { id: "JOB-002", title: "Underground Mining Engineer", department: "Engineering", location: "Carletonville", type: "Permanent", applicants: 7, salary: "R80k–R110k/mo", posted: "2026-06-14", status: "Active", description: "Responsible for planning, design, and implementation of underground mining methods to achieve safe, efficient ore extraction.", requirements: ["BEng Mining Engineering", "Government Certificate of Competency", "3+ years underground experience", "Rock mechanics knowledge"] },
  { id: "JOB-003", title: "Rock Mechanics Specialist", department: "Safety", location: "Witbank", type: "Contract", applicants: 4, salary: "R65k–R85k/mo", posted: "2026-06-08", status: "Closing Soon", description: "Specialist role focused on underground strata control, hazard identification, and rock engineering risk management.", requirements: ["BSc/BEng Geology or Mining Engineering", "Rock Mechanics certification", "5+ years relevant experience"] },
  { id: "JOB-004", title: "Ventilation Officer", department: "Safety", location: "Klerksdorp", type: "Permanent", applicants: 19, salary: "R50k–R70k/mo", posted: "2026-05-28", status: "Filled", description: "Manage and monitor underground ventilation systems to ensure compliance with MHSA ventilation regulations.", requirements: ["Diploma in Mine Ventilation or equivalent", "Ventilation Officer Certificate", "2+ years experience"] },
  { id: "JOB-005", title: "SHEQ Manager", department: "HSE", location: "Johannesburg", type: "Permanent", applicants: 31, salary: "R90k–R120k/mo", posted: "2026-06-01", status: "Active", description: "Lead the SHEQ function across all operations, driving a zero-harm culture and ensuring full statutory compliance.", requirements: ["BSc/BEng or equivalent", "SAMTRAC or NEBOSH", "10+ years SHEQ experience in mining", "Strong knowledge of MHSA"] },
];

export const applicantsData = [
  { id: "APP-001", name: "Ntombi Dlamini", job: "JOB-001", stage: "Interview", score: 88, location: "Pretoria", email: "ntombi.dlamini@email.com", phone: "+27 82 111 2222", experience: "6 years", education: "B.Tech Mine Surveying, TUT", summary: "Experienced mine surveyor with strong underground background and proficiency in Surpac. Currently employed at Sibanye-Stillwater." },
  { id: "APP-002", name: "Sipho Nkosi", job: "JOB-002", stage: "Applied", score: 72, location: "Johannesburg", email: "sipho.nkosi@email.com", phone: "+27 73 222 3333", experience: "3 years", education: "BEng Mining Engineering, Wits", summary: "Recent graduate with 3 years experience at an opencast colliery, looking to transition to hard-rock underground mining." },
  { id: "APP-003", name: "Anita Pillay", job: "JOB-005", stage: "Offer", score: 95, location: "Sandton", email: "anita.pillay@email.com", phone: "+27 84 333 4444", experience: "12 years", education: "BSc Safety Management, UNISA", summary: "Seasoned SHEQ professional with 12 years in platinum and gold mining. SAMTRAC and ISO 45001 Lead Auditor certified." },
  { id: "APP-004", name: "Thabo Molefe", job: "JOB-001", stage: "Screening", score: 81, location: "Rustenburg", email: "thabo.molefe@email.com", phone: "+27 71 444 5555", experience: "4 years", education: "B.Tech Mine Surveying, NWU", summary: "Motivated mine surveyor with experience in both shaft and reef development surveying in the Bushveld Complex." },
  { id: "APP-005", name: "Reza Patel", job: "JOB-003", stage: "Interview", score: 77, location: "Witbank", email: "reza.patel@email.com", phone: "+27 79 555 6666", experience: "7 years", education: "BSc Geology, UP", summary: "Rock mechanics specialist with extensive experience in deep-level gold and coal mines, including seismic hazard assessment." },
];

export const csiProjectsData = [
  { id: "CSI-001", name: "Limpopo Youth Skills Programme", category: "Skills Development", budget: 2400000, spent: 1800000, beneficiaries: 340, status: "Active", phase: "Phase 2", location: "Polokwane", description: "A 24-month TVET partnership programme providing accredited artisan and technical training to youth within 50km of our Limpopo operations.", manager: "Maria Sithole", startDate: "2025-03-01", endDate: "2027-02-28", milestones: ["Phase 1 complete – 180 learners enrolled", "Phase 2 launched – 160 new learners", "Phase 3 planned – Advanced trades"] },
  { id: "CSI-002", name: "Rustenburg Water Infrastructure", category: "Infrastructure", budget: 5100000, spent: 5100000, beneficiaries: 4200, status: "Completed", phase: "Done", location: "Rustenburg", description: "Construction of a 12km water pipeline connecting 4 rural communities to the municipal grid, in partnership with the Bojanala Platinum District Municipality.", manager: "John Khumalo", startDate: "2024-01-15", endDate: "2025-11-30", milestones: ["Environmental impact study complete", "Pipeline construction complete", "Final inspection passed", "Handover to municipality"] },
  { id: "CSI-003", name: "Local SMME Procurement Drive", category: "Enterprise Dev.", budget: 800000, spent: 320000, beneficiaries: 18, status: "Active", phase: "Phase 1", location: "Carletonville", description: "Identifying, mentoring, and developing local SMMEs to qualify as suppliers within our supply chain, with a focus on black-owned businesses.", manager: "Busi Mokoena", startDate: "2026-01-10", endDate: "2026-12-31", milestones: ["18 SMMEs identified and assessed", "Supplier development workshops started"] },
  { id: "CSI-004", name: "Mine Community Health Clinic", category: "Healthcare", budget: 3800000, spent: 1200000, beneficiaries: 8600, status: "Planning", phase: "Pre-Build", location: "Witbank", description: "Construction of a 300m² primary healthcare clinic serving 6 surrounding communities, staffed in partnership with the Department of Health.", manager: "Dr. Fatima Hassan", startDate: "2026-07-01", endDate: "2028-06-30", milestones: ["Site selection complete", "Architect appointed", "Environmental waiver in progress"] },
  { id: "CSI-005", name: "Women in Mining Bursary Fund", category: "Education", budget: 1200000, spent: 600000, beneficiaries: 24, status: "Active", phase: "Ongoing", location: "Nationwide", description: "Annual bursary fund supporting women pursuing undergraduate qualifications in mining engineering, geology, and metallurgy at South African universities.", manager: "Community Admin", startDate: "2025-01-01", endDate: "2027-12-31", milestones: ["2025 cohort: 12 bursaries awarded", "2026 cohort: 12 bursaries awarded"] },
];
